name: Run tests

on:
  # Authorize manual trigger
  workflow_dispatch:
  # Authorize this workflow to be called by another
  workflow_call:
  push:
    branches:
      - main


jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12.x', '14.x', '16.x' ]
    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          # If package-lock.json file hash changed, then invalidate cache
          key: npm-${{ matrix.node }}-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        # If cache has been used, then no installation
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run tests
        run: npm test
